apiVersion: v1
kind: Secret
metadata:
  name: ali-juicefs-secret
  namespace: default
  labels:
    # 增加该标签以启用认证信息校验
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: ali-juicefs-secret
  metaurl: postgres://postgres:postgres@host:port/juicefs
  storage: s3
  bucket: https://xx.oss-cn-hangzhou.aliyuncs.com
  access-key: xx
  secret-key: xx
  # 设置 Mount Pod 时区，默认为 UTC。
  envs: "{TZ: Asia/Shanghai}"
  # 如需在 Mount Pod 中创建文件系统，也可以将更多 juicefs format 参数填入 format-options。
  format-options: trash-days=7,block-size=4096
