version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.1-management
    container_name: rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
      - "${RABBITMQ_PROMETHEUS_PORT}:15692"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ${BASE_DATA}/rabbitmq:/var/lib/rabbitmq
